Music Library System/Controllers/LibraryController.cs
using Microsoft.AspNetCore.Mvc;
using Music_Library_System.Models;
using System.Collections.Generic;
using System.Linq;

namespace Music_Library_System.Controllers
{
    public class LibraryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Albums()
        {
            var albums = new List<Album>
            {
                new Album { 
                    Id = 1, 
                    Title = "Thriller", 
                    Description = "Michael Jackson's iconic album",
                    CoverImageUrl = "https://picsum.photos/id/1/300/300", 
                    ReleaseDate = new DateTime(1982, 11, 30),
                    Genre = "Pop",
                    Artist = new Artist { Id = 1, Name = "Michael Jackson" },
                    Songs = new List<Song>()
                },
                new Album { 
                    Id = 2, 
                    Title = "Back in Black", 
                    Description = "AC/DC's legendary album",
                    CoverImageUrl = "https://picsum.photos/id/2/300/300", 
                    ReleaseDate = new DateTime(1980, 7, 25),
                    Genre = "Rock",
                    Artist = new Artist { Id = 2, Name = "AC/DC" },
                    Songs = new List<Song>()
                },
                new Album { 
                    Id = 3, 
                    Title = "The Dark Side of the Moon", 
                    Description = "Pink Floyd's masterpiece",
                    CoverImageUrl = "https://picsum.photos/id/3/300/300", 
                    ReleaseDate = new DateTime(1973, 3, 1),
                    Genre = "Progressive Rock",
                    Artist = new Artist { Id = 3, Name = "Pink Floyd" },
                    Songs = new List<Song>()
                },
                new Album { 
                    Id = 4, 
                    Title = "Abbey Road", 
                    Description = "The Beatles' final album",
                    CoverImageUrl = "https://picsum.photos/id/4/300/300", 
                    ReleaseDate = new DateTime(1969, 9, 26),
                    Genre = "Rock",
                    Artist = new Artist { Id = 4, Name = "The Beatles" },
                    Songs = new List<Song>()
                }
            };

            return View(albums);
        }

        public IActionResult Artists()
        {
            var artists = new List<Artist>
            {
                new Artist { 
                    Id = 1, 
                    Name = "Michael Jackson", 
                    Biography = "The King of Pop",
                    ImageUrl = "https://picsum.photos/id/5/300/300", 
                    Genre = "Pop",
                    Country = "USA",
                    BirthDate = new DateTime(1958, 8, 29),
                    Albums = new List<Album>(),
                    Songs = new List<Song>()
                },
                new Artist { 
                    Id = 2, 
                    Name = "AC/DC", 
                    Biography = "Australian rock band",
                    ImageUrl = "https://picsum.photos/id/6/300/300", 
                    Genre = "Rock",
                    Country = "Australia",
                    Albums = new List<Album>(),
                    Songs = new List<Song>()
                },
                new Artist { 
                    Id = 3, 
                    Name = "Pink Floyd", 
                    Biography = "English progressive rock band",
                    ImageUrl = "https://picsum.photos/id/7/300/300", 
                    Genre = "Progressive Rock",
                    Country = "UK",
                    Albums = new List<Album>(),
                    Songs = new List<Song>()
                },
                new Artist { 
                    Id = 4, 
                    Name = "The Beatles", 
                    Biography = "English rock band",
                    ImageUrl = "https://picsum.photos/id/8/300/300", 
                    Genre = "Rock",
                    Country = "UK",
                    Albums = new List<Album>(),
                    Songs = new List<Song>()
                }
            };

            return View(artists);
        }

        public IActionResult Songs(string genre = null, string search = null)
        {
            var allSongs = new List<Song>
            {
                new Song { 
                    Id = 1, 
                    Title = "Billie Jean", 
                    Duration = "4:54", 
                    Genre = "Pop",
                    AudioUrl = "https://example.com/songs/billie-jean.mp3",
                    Lyrics = "She was more like a beauty queen...",
                    TrackNumber = 1,
                    Artist = new Artist { Id = 1, Name = "Michael Jackson" },
                    Album = new Album { Id = 1, Title = "Thriller", CoverImageUrl = "https://picsum.photos/id/1/400/400" }
                },
                new Song { 
                    Id = 2, 
                    Title = "Back in Black", 
                    Duration = "4:15", 
                    Genre = "Rock",
                    AudioUrl = "https://example.com/songs/back-in-black.mp3",
                    Lyrics = "Back in black...",
                    TrackNumber = 1,
                    Artist = new Artist { Id = 2, Name = "AC/DC" },
                    Album = new Album { Id = 2, Title = "Back in Black", CoverImageUrl = "https://picsum.photos/id/2/400/400" }
                },
                new Song { 
                    Id = 3, 
                    Title = "Money", 
                    Duration = "6:22", 
                    Genre = "Progressive Rock",
                    AudioUrl = "https://example.com/songs/money.mp3",
                    Lyrics = "Money, get away...",
                    TrackNumber = 6,
                    Artist = new Artist { Id = 3, Name = "Pink Floyd" },
                    Album = new Album { Id = 3, Title = "The Dark Side of the Moon", CoverImageUrl = "https://picsum.photos/id/3/400/400" }
                },
                new Song { 
                    Id = 4, 
                    Title = "Come Together", 
                    Duration = "4:19", 
                    Genre = "Rock",
                    AudioUrl = "https://example.com/songs/come-together.mp3",
                    Lyrics = "Here come old flat top...",
                    TrackNumber = 1,
                    Artist = new Artist { Id = 4, Name = "The Beatles" },
                    Album = new Album { Id = 4, Title = "Abbey Road", CoverImageUrl = "https://picsum.photos/id/4/400/400" }
                },
                new Song { 
                    Id = 5, 
                    Title = "Summer Vibes", 
                    Duration = "3:45", 
                    Genre = "Electronic",
                    AudioUrl = "https://example.com/songs/summer-vibes.mp3",
                    Lyrics = "Summer vibes...",
                    TrackNumber = 1,
                    Artist = new Artist { Id = 5, Name = "DJ Cool" },
                    Album = new Album { Id = 5, Title = "Summer Hits", CoverImageUrl = "https://picsum.photos/id/5/400/400" }
                },
                new Song { 
                    Id = 6, 
                    Title = "Midnight Dreams", 
                    Duration = "4:20", 
                    Genre = "Ambient",
                    AudioUrl = "https://example.com/songs/midnight-dreams.mp3",
                    Lyrics = "Midnight dreams...",
                    TrackNumber = 2,
                    Artist = new Artist { Id = 6, Name = "Ambient Master" },
                    Album = new Album { Id = 6, Title = "Night Sounds", CoverImageUrl = "https://picsum.photos/id/6/400/400" }
                }
            };

            // Always get all genres for the filter buttons
            ViewBag.Genres = allSongs.Select(s => s.Genre).Distinct().ToList();

            var songs = allSongs;
            if (!string.IsNullOrEmpty(genre))
            {
                songs = songs.Where(s => s.Genre.Equals(genre, System.StringComparison.OrdinalIgnoreCase)).ToList();
            }
            if (!string.IsNullOrEmpty(search))
            {
                songs = songs.Where(s =>
                    s.Title.Contains(search, System.StringComparison.OrdinalIgnoreCase) ||
                    s.Artist.Name.Contains(search, System.StringComparison.OrdinalIgnoreCase) ||
                    s.Album.Title.Contains(search, System.StringComparison.OrdinalIgnoreCase)
                ).ToList();
            }

            ViewBag.SelectedGenre = genre;
            ViewBag.Search = search;
            return View(songs);
        }

        public IActionResult FilterSongsByGenre(string genre, string search = null)
        {
            var allSongs = new List<Song>
            {
                new Song { 
                    Id = 1, 
                    Title = "Billie Jean", 
                    Duration = "4:54", 
                    Genre = "Pop",
                    AudioUrl = "https://example.com/songs/billie-jean.mp3",
                    Lyrics = "She was more like a beauty queen...",
                    TrackNumber = 1,
                    Artist = new Artist { Id = 1, Name = "Michael Jackson" },
                    Album = new Album { Id = 1, Title = "Thriller", CoverImageUrl = "https://picsum.photos/id/1/400/400" }
                },
                new Song { 
                    Id = 2, 
                    Title = "Back in Black", 
                    Duration = "4:15", 
                    Genre = "Rock",
                    AudioUrl = "https://example.com/songs/back-in-black.mp3",
                    Lyrics = "Back in black...",
                    TrackNumber = 1,
                    Artist = new Artist { Id = 2, Name = "AC/DC" },

Music Library System/Controllers/PlaylistController.cs
using Microsoft.AspNetCore.Mvc;
using Music_Library_System.Models;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System;

namespace Music_Library_System.Controllers
{
    public class PlaylistController : Controller
    {
        private static List<Playlist> Playlists = null;
        private static int NextId = 4;

        private void EnsureDefaultPlaylists()
        {
            if (Playlists == null)
            {
                Playlists = new List<Playlist>
                {
                    new Playlist { 
                        Id = 1, 
                        Name = "Rock Classics", 
                        Description = "Best rock songs of all time", 
                        CoverImageUrl = "https://picsum.photos/id/669/400/400",
                        IsPublic = true,
                        UserProfile = new UserProfile { Id = 1, Username = "user1" },
                        Songs = new List<Song>()
                    },
                    new Playlist { 
                        Id = 2, 
                        Name = "Chill Vibes", 
                        Description = "Relaxing music for study sessions", 
                        CoverImageUrl = "https://picsum.photos/id/69/400/400",
                        IsPublic = true,
                        UserProfile = new UserProfile { Id = 1, Username = "user1" },
                        Songs = new List<Song>()
                    },
                    new Playlist { 
                        Id = 3, 
                        Name = "Workout Mix", 
                        Description = "High energy tracks for your workout", 
                        CoverImageUrl = "https://picsum.photos/id/67/400/400",
                        IsPublic = true,
                        UserProfile = new UserProfile { Id = 1, Username = "user1" },
                        Songs = new List<Song>()
                    }
                };
            }
        }

        public IActionResult Index()
        {
            EnsureDefaultPlaylists();
            return View(Playlists);
        }

        public IActionResult Details(int id)
        {
            EnsureDefaultPlaylists();
            var playlist = Playlists.FirstOrDefault(p => p.Id == id);
            if (playlist == null)
                return NotFound();

            // For demo, add some songs if empty
            if (playlist.Songs == null || !playlist.Songs.Any())
            {
                playlist.Songs = new List<Song>
                {
                    new Song { 
                        Id = 1, 
                        Title = "Back in Black", 
                        Duration = "4:15", 
                        Genre = "Rock",
                        AudioUrl = "https://example.com/songs/back-in-black.mp3",
                        Lyrics = "Back in black...",
                        TrackNumber = 1,
                        Artist = new Artist { 
                            Id = 2, 
                            Name = "AC/DC",
                            ImageUrl = "https://picsum.photos/id/237/400/400"
                        },
                        Album = new Album { 
                            Id = 2, 
                            Title = "Back in Black",
                            CoverImageUrl = "https://picsum.photos/id/238/400/400"
                        }
                    },
                    new Song { 
                        Id = 2, 
                        Title = "Smoke on the Water", 
                        Duration = "5:40", 
                        Genre = "Rock",
                        AudioUrl = "https://example.com/songs/smoke-on-the-water.mp3",
                        Lyrics = "We all came out to Montreux...",
                        TrackNumber = 1,
                        Artist = new Artist { 
                            Id = 5, 
                            Name = "Deep Purple",
                            ImageUrl = "https://picsum.photos/id/239/400/400"
                        },
                        Album = new Album { 
                            Id = 5, 
                            Title = "Machine Head",
                            CoverImageUrl = "https://picsum.photos/id/240/400/400"
                        }
                    },
                    new Song { 
                        Id = 3, 
                        Title = "Stairway to Heaven", 
                        Duration = "8:02", 
                        Genre = "Rock",
                        AudioUrl = "https://example.com/songs/stairway-to-heaven.mp3",
                        Lyrics = "There's a lady who's sure...",
                        TrackNumber = 4,
                        Artist = new Artist { 
                            Id = 6, 
                            Name = "Led Zeppelin",
                            ImageUrl = "https://picsum.photos/id/241/400/400"
                        },
                        Album = new Album { 
                            Id = 6, 
                            Title = "Led Zeppelin IV",
                            CoverImageUrl = "https://picsum.photos/id/242/400/400"
                        }
                    }
                };
            }

            ViewBag.Songs = playlist.Songs;
            return View(playlist);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var session = HttpContext.Session.GetString("UserSession");
            if (string.IsNullOrEmpty(session))
            {
                TempData["AuthMessage"] = "You must log in or sign up to create a playlist.";
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Create(string Name, string Description, string CoverImageUrl, bool IsPublic)
        {
            EnsureDefaultPlaylists();
            var newPlaylist = new Playlist
            {
                Id = NextId++,
                Name = Name,
                Description = Description,
                CoverImageUrl = string.IsNullOrWhiteSpace(CoverImageUrl) ? 
                    $"https://picsum.photos/id/{new Random().Next(1, 1000)}/400/400" : 
                    CoverImageUrl,
                IsPublic = IsPublic,
                UserProfile = new UserProfile { Id = 1, Username = "user1" }, // For demo, static user
                Songs = new List<Song>(),
                CreatedAt = DateTime.Now
            };
            Playlists.Add(newPlaylist);
            return RedirectToAction("Index");
        }
    }
}

Music Library System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Music Library System</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/dark-theme.css" />
    <style>
        html, body {
            height: 100%;
        }
        body {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }
        .main-content {
            flex: 1 0 auto;
        }
        footer {
            flex-shrink: 0;
        }
    </style>
</head>
<body class="bg-dark text-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/assets/icon.svg" alt="SoundCloud" width="30" height="30" class="d-inline-block align-top me-2" /> SoundCloud
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Library" asp-action="Index">Library</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Playlist" asp-action="Index">Playlists</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <form class="d-flex me-2">
                            <input class="form-control bg-dark text-light me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-light" type="submit"><i class="bi bi-search"></i></button>
                        </form>
                        @{
                            var session = Context.Session.GetString("UserSession");
                            if (session != null)
                            {
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" id="profileDropdown" data-bs-toggle="dropdown" aria-expanded="false" style="background: #FF6B00; border: none;">
                                        <i class="bi bi-person-circle"></i> Profile
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
                                        <li><a class="dropdown-item" asp-controller="Account" asp-action="Profile">View Profile</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a></li>
                                    </ul>
                                </div>
                            }
                            else
                            {
                                <a href="/Account/Login" class="btn btn-primary me-2" style="background: #FF6B00; border: none;">Sign In</a>
                                <a href="/Account/Register" class="btn btn-outline-light">Sign Up</a>
                            }
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container main-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light bg-black mt-auto">
        <div class="container">
            &copy; 2025 - Music Library System - Created by Afsah Ur Rehman Zaidi - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-light">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>